### ISSUE TITLE
Security hardsuit armor value changes need to be properly commented.

### ISSUE THREAD

**Issue by Zap527** [ss14-harmony/ss14-harmony#562]
## Description
Comments concerning security hardsuit harmony changes are extremely non-descriptive and don't even tell you what changed from upstream.

```yml
# Harmony change. Adjusted damage resistance values
#Security Hardsuit
- type: entity
  parent: [ClothingOuterHardsuitBase, BaseSecurityContraband]
  id: ClothingOuterHardsuitSecurity
  name: security hardsuit
  description: A special suit that protects against hazardous, low pressure environments. Has an additional layer of armor.
[...]
```
